name: Test Linux

on:
  workflow_dispatch:
    inputs:
      build-type:
        description: Build Configuration
        default: Release
        type: choice
        options:
          - Debug
          - Release
      test-category:
        description: Category of tests
        default: Simple
        type: choice
        options:
          - Simple
          - Game
  workflow_call:
    inputs:
      build-type:
        default: Release
        type: string
      test-category:
        default: Simple
        type: string

concurrency:
  group: test-linux-${{ github.event.pull_request.number || github.ref }}-${{ github.event.inputs.build-type || inputs.build-type || 'Debug' }}-${{ github.event.inputs.test-category || inputs.test-category || 'Simple' }}
  cancel-in-progress: true

jobs:
  #
  # Test Stride on Linux
  #
  Linux-Tests:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'workflow_call' || github.event.pull_request.draft == false }}
    name: Test (${{ github.event.inputs.build-type || inputs.build-type }}, ${{ github.event.inputs.test-category || inputs.test-category || 'Simple' }})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          lfs: true
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'
      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libbsd-dev clang llvm lld
      - name: Patch NativePath for Linux
        run: |
          # Make strlcat_chk and strlcpy_chk non-fatal on Linux
          sed -i 's/#if !__has_builtin(__builtin___strlcat_chk)/#if !__has_builtin(__builtin___strlcat_chk) \&\& !defined(__linux__)/' deps/NativePath/NativePath.h
          sed -i 's/#if !__has_builtin(__builtin___strlcpy_chk)/#if !__has_builtin(__builtin___strlcpy_chk) \&\& !defined(__linux__)/' deps/NativePath/NativePath.h
      - name: Create NuGet.config for local packages
        run: |
          WORKSPACE_PATH="$(pwd)"
          LOCAL_PACKAGES_PATH="$WORKSPACE_PATH/bin/packages"
          GLOBAL_PACKAGES_PATH="$HOME/.local/share/Stride/NuGetDev"

          echo "Creating nuget.config with:"
          echo "  Local packages: $LOCAL_PACKAGES_PATH"
          echo "  Global packages: $GLOBAL_PACKAGES_PATH"
          echo "  Workspace: $WORKSPACE_PATH"

          cat > nuget.config << EOF
          <?xml version="1.0" encoding="utf-8"?>
          <configuration>
            <packageSources>
              <add key="StrideDev Local" value="$LOCAL_PACKAGES_PATH" />
              <add key="StrideDev Global" value="$GLOBAL_PACKAGES_PATH" />
              <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
            </packageSources>

            <packageSourceMapping>
              <!-- Look first in locally-built packages directory -->
              <packageSource key="StrideDev Local">
                <package pattern="Stride*" />
                <package pattern="Stride.*" />
              </packageSource>
              <packageSource key="StrideDev Global">
                <package pattern="Stride*" />
                <package pattern="Stride.*" />
              </packageSource>
              <!-- Fallback to NuGet for anything else -->
              <packageSource key="nuget.org">
                <package pattern="Stride*" />
                <package pattern="Stride.*" />
                <package pattern="*" />
              </packageSource>
            </packageSourceMapping>
          </configuration>
          EOF

          echo ""
          echo "NuGet.config created:"
          cat nuget.config
      - name: Verify local package directory
        run: |
          echo "Checking for local packages directory..."
          if [ -d "./bin/packages" ]; then
            echo "Local packages directory exists:"
            ls -lah ./bin/packages || echo "Directory exists but is empty or cannot list"
          else
            echo "WARNING: Local packages directory ./bin/packages does not exist yet"
            echo "Creating directory..."
            mkdir -p ./bin/packages
          fi
          echo "Current directory: $(pwd)"

          # Also create the global packages directory if it doesn't exist
          GLOBAL_PKG_DIR="$HOME/.local/share/Stride/NuGetDev"
          if [ ! -d "$GLOBAL_PKG_DIR" ]; then
            echo "Creating global packages directory: $GLOBAL_PKG_DIR"
            mkdir -p "$GLOBAL_PKG_DIR"
          fi
      - name: Build
        run: |
          dotnet build build/Stride.Tests.${{ github.event.inputs.test-category || inputs.test-category || 'Simple' }}.slnf \
            -restore -m:1 -nr:false \
            -v:m -p:WarningLevel=0 \
            -p:Configuration=${{ github.event.inputs.build-type || inputs.build-type }} \
            -p:StridePlatforms=Linux \
            -p:StrideGraphicsApis=OpenGL
      - name: Verify packages after build
        run: |
          echo "Checking local packages after build..."
          if [ -d "./bin/packages" ]; then
            echo "Packages found:"
            find ./bin/packages -name "*.nupkg" -type f
          else
            echo "Local packages directory still does not exist"
          fi
      - name: Test
        run: |
          dotnet test build/Stride.Tests.${{ github.event.inputs.test-category || inputs.test-category || 'Simple' }}.slnf \
            --no-build \
            -p:Configuration=${{ github.event.inputs.build-type || inputs.build-type }}
